import type { Metadata } from "next";
import { inter, dm_sans, dm_mono, dm_serif_display } from './fonts';
import './globals.css';
import Footer from "../component/Footer";
import NavBar from "../component/navbar";



export const metadata: Metadata = {
  title: "September Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       className={`${inter.variable} ${dm_sans.variable} ${dm_mono.variable} ${dm_serif_display.variable}`}
      ><NavBar/>
        <main className=" bg-amber-50">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
